[[env]]
name = "KEYBALL_ROOT"
eval = "$(git rev-parse --show-toplevel)"

[[env]]
name = "QMK_HOME"
eval = "$KEYBALL_ROOT/__qmk__"

[[commands]]
package = "qmk"

[[commands]]
name = "setup"
help = "Setup QMK firmware"
command = '''
qmk setup -b 0.16.3 -y
ln -sf -t "$QMK_HOME/keyboards/" "$KEYBALL_ROOT/qmk_firmware/keyboards/keyball"
'''

[[commands]]
name = "compile"
help = "Compile firmware"
command = '''
qmk compile -j 4 -kb keyball/keyball44 -km misawa
'''

[[commands]]
name = "flash"
help = "Flash firmware"
command = '''
qmk flash -kb keyball/keyball44 -km misawa
'''

[[commands]]
name = "format"
help = "Fomrat my firmware files"
command = '''
clang-format "-style=file:$QMK_HOME/.clang-format" -i "$KEYBALL_ROOT/qmk_firmware/keyboards/keyball/keyball44/keymaps/misawa/"*.{c,h}
'''
